---
- name: Linux Environment Configuration
  hosts: localhost
  become: yes
  vars_files:
    - files/dnf.yml
    - files/script-installs.yml
  tasks:
    - name: install DNF packages
      ansible.builtin.dnf:
        state: present
        name: "{{ item }}"
      loop: "{{ dnf_packages }}"
#    - name: run scripts to install non-packaged apps
#      ansible.builtin.shell: "{{ item }}"
#      with_items: "{{ script_install_command }}"
